### ISSUE TITLE
question regarding LDA analysis details

### ISSUE THREAD

**Issue by Liesy** [HumanCompatibleAI/tensor-trust-data#2]
Hi, thank you for your excellent work!

I noticed that you have clustered attack samples into 16 topics in the paper but there is no relevant information displayed in this repo, so could you release the code or data for this part?

Thank you very much.

**Comment by AliengirlLiv** [comment]
[Here is the code we used.](https://github.com/HumanCompatibleAI/tensor-trust/blob/main/notebooks/LDA_Clean.ipynb)

Note that the stage where we combined semantically similar clusters (i.e. where we create the "Topic" enum was done manually.

**Comment by Liesy** [comment]
Thank you very much!
